services:
  - type: web
    name: smart-care-backend
    env: python
    plan: starter
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.server:app -w 2 -b 0.0.0.0:3000"
    envVars:
      - key: SERVING_URL
        sync: false
      - key: DBRX_PAT
        sync: false
      - key: ALLOW_ORIGIN
        value: "*"
  
  - type: web
    name: smart-care-frontend
    env: static
    plan: starter
    region: oregon
    rootDir: frontend
    buildCommand: "echo 'Frontend build complete'"
    staticPublishPath: .
