services:
  - type: web
    name: smart-care-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app -w 2 -b 0.0.0.0:3000
    envVars:
      - key: SERVING_URL
        sync: false
      - key: DBRX_PAT
        sync: false
      - key: ALLOW_ORIGIN
        value: "*"
  
  - type: web
    name: smart-care-frontend
    env: static
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: "echo 'Frontend build complete'"
    staticPublishPath: .
