name: Daily Render Redeploy

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/v1/services/<YOUR_SERVICE_ID>/deploys \
            -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
            -H 'Content-Type: application/json'
